### ISSUE TITLE
enhance Future<void> updateMockLocation( double latitude, double longitude ) to mock also height

### ISSUE THREAD

**Issue by t-m-z** [dariocavada/fluttermocklocation#1]
the new method should be

Future<void> updateMockLocation( double latitude, double longitude, double height)

**Comment by dariocavada** [comment]
I've added `altitude` as an optional parameter:

```dart
Future<void> updateMockLocation(double latitude, double longitude, {double altitude = 0})
```

This ensures backward compatibility while allowing you to specify altitude if needed. 
Please let me know if you encounter any issues with this update!

**Comment by t-m-z** [comment]
Thank you for this quick response. Up to now I did not encounter any issues. However I am on a business trip and cannot test  as deep as I want to.
Hopefully I will chech it at the weekend at home.
Kind regards
